"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TokenType = void 0;
var TokenType;
(function (TokenType) {
    TokenType["TOKEN_STRING"] = "string";
    TokenType["TOKEN_WHITESPACE"] = "whitespace";
    TokenType["TOKEN_DATA"] = "data";
    TokenType["TOKEN_BLOCK_START"] = "block-start";
    TokenType["TOKEN_BLOCK_END"] = "block-end";
    TokenType["TOKEN_VARIABLE_START"] = "variable-start";
    TokenType["TOKEN_VARIABLE_END"] = "variable-end";
    TokenType["TOKEN_COMMENT"] = "comment";
    TokenType["TOKEN_LEFT_PAREN"] = "left-paren";
    TokenType["TOKEN_RIGHT_PAREN"] = "right-paren";
    TokenType["TOKEN_LEFT_BRACKET"] = "left-bracket";
    TokenType["TOKEN_RIGHT_BRACKET"] = "right-bracket";
    TokenType["TOKEN_LEFT_CURLY"] = "left-curly";
    TokenType["TOKEN_RIGHT_CURLY"] = "right-curly";
    TokenType["TOKEN_OPERATOR"] = "operator";
    TokenType["TOKEN_COMMA"] = "comma";
    TokenType["TOKEN_COLON"] = "colon";
    TokenType["TOKEN_TILDE"] = "tilde";
    TokenType["TOKEN_PIPE"] = "pipe";
    TokenType["TOKEN_INT"] = "int";
    TokenType["TOKEN_FLOAT"] = "float";
    TokenType["TOKEN_BOOLEAN"] = "boolean";
    TokenType["TOKEN_NONE"] = "none";
    TokenType["TOKEN_SYMBOL"] = "symbol";
    TokenType["TOKEN_SPECIAL"] = "special";
    TokenType["TOKEN_REGEX"] = "regex";
})(TokenType = exports.TokenType || (exports.TokenType = {}));
//# sourceMappingURL=tokenType.js.map