export enum TokenType {
  TOKEN_STRING = 'string',
  TOKEN_WHITESPACE = 'whitespace',
  TOKEN_DATA = 'data',
  TOKEN_BLOCK_START = 'block-start',
  TOKEN_BLOCK_END = 'block-end',
  TOKEN_VARIABLE_START = 'variable-start',
  TOKEN_VARIABLE_END = 'variable-end',
  TOKEN_COMMENT = 'comment',
  TOKEN_LEFT_PAREN = 'left-paren',
  TOKEN_RIGHT_PAREN = 'right-paren',
  TOKEN_LEFT_BRACKET = 'left-bracket',
  TOKEN_RIGHT_BRACKET = 'right-bracket',
  TOKEN_LEFT_CURLY = 'left-curly',
  TOKEN_RIGHT_CURLY = 'right-curly',
  TOKEN_OPERATOR = 'operator',
  TOKEN_COMMA = 'comma',
  TOKEN_COLON = 'colon',
  TOKEN_TILDE = 'tilde',
  TOKEN_PIPE = 'pipe',
  TOKEN_INT = 'int',
  TOKEN_FLOAT = 'float',
  TOKEN_BOOLEAN = 'boolean',
  TOKEN_NONE = 'none',
  TOKEN_SYMBOL = 'symbol',
  TOKEN_SPECIAL = 'special',
  TOKEN_REGEX = 'regex',
}
